project 'Arcanoid.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Arcanoid' do

  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'

  # Pods for Arcanoid

end
